import QtQuick
import QtQuick3D

// Thin printed artwork surface. Circular labels preserve the physical center hub
// through a static alpha mask texture (generated by tools/music_devices/generate.py)
// instead of a per-surface Canvas + OpacityMask chain of offscreen layers.
Model {
    id: surface
    property url artSource: ""
    property url maskSource: ""
    source: "#Rectangle"
    materials: PrincipledMaterial {
        baseColorMap: Texture {
            sourceItem: MusicDeviceCover {
                width: 512; height: 512
                artSource: surface.artSource
            }
        }
        opacityMap: surface.maskSource.toString() !== "" ? mask : null
        metalness: 0
        roughness: .7
        alphaMode: PrincipledMaterial.Blend
        cullMode: Material.NoCulling
    }
    Texture {
        id: mask
        source: surface.maskSource
    }
}
